<a href="https://colab.research.google.com/github/JonahDG/DataAnalysisRecipes/blob/master/DataAnalysisExercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plot
import scipy as sp
table1=np.array([[201,592,61,9,-.84],
                 [244,401,25,4,.31],
                 [47, 583,38,11,.64],
                 [287,402,15,7,-.27],
                 [203,495,21,5,-.33],
                 [58,173,15,9,.67],
                 [210,479,27,4,-.02],
                 [202,504,14,4,-.05],
                 [198,510,30,11,-.84],
                 [158,416,16,7,-.69],
                 [165,393,14,5,.30],
                 [201,442,25,5,-.46],
                 [157,317,52,5,-.03],
                 [131,311,16,6,.50],
                 [166,400,34,6,.73],
                 [160,337,31,5,-.52],
                 [186,423,42,9,.9],
                 [125,334,26,8,.4],
                 [218,533,16,6,-.78],
                 [146,344,22,5,-.56]])
print(table1)

[[ 2.01e+02  5.92e+02  6.10e+01  9.00e+00 -8.40e-01]
 [ 2.44e+02  4.01e+02  2.50e+01  4.00e+00  3.10e-01]
 [ 4.70e+01  5.83e+02  3.80e+01  1.10e+01  6.40e-01]
 [ 2.87e+02  4.02e+02  1.50e+01  7.00e+00 -2.70e-01]
 [ 2.03e+02  4.95e+02  2.10e+01  5.00e+00 -3.30e-01]
 [ 5.80e+01  1.73e+02  1.50e+01  9.00e+00  6.70e-01]
 [ 2.10e+02  4.79e+02  2.70e+01  4.00e+00 -2.00e-02]
 [ 2.02e+02  5.04e+02  1.40e+01  4.00e+00 -5.00e-02]
 [ 1.98e+02  5.10e+02  3.00e+01  1.10e+01 -8.40e-01]
 [ 1.58e+02  4.16e+02  1.60e+01  7.00e+00 -6.90e-01]
 [ 1.65e+02  3.93e+02  1.40e+01  5.00e+00  3.00e-01]
 [ 2.01e+02  4.42e+02  2.50e+01  5.00e+00 -4.60e-01]
 [ 1.57e+02  3.17e+02  5.20e+01  5.00e+00 -3.00e-02]
 [ 1.31e+02  3.11e+02  1.60e+01  6.00e+00  5.00e-01]
 [ 1.66e+02  4.00e+02  3.40e+01  6.00e+00  7.30e-01]
 [ 1.60e+02  3.37e+02  3.10e+01  5.00e+00 -5.20e-01]
 [ 1.86e+02  4.23e+02  4.20e+01  9.00e+00  9.00e-01]
 [ 1.25e+02  3.34e+02  2.60e+01  8.00e+00  4.00e-01]
 [ 2.18e+02  5.33e+02  1.60e+01  6.00e+00 -7.8

# Exercise 1